services:
  db:
    image: postgres:13
    environment :
      POSTGRES_USER: user_zero
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ToDoRestful
    ports:
    - "5435:5432"

  app:
    build: .
    ports:
    - "8080:8080"
    environment:
    - TODO_DB=postgres://user_zero:password@db:5432/ToDoRestful?sslmode=disable
    volumes:
    - ./migrations:/app/migrations
    depends_on:
    - db